on:
  push:
    branches:
      - main
name: 🚀 Deploy website Production
jobs:
  web-deploy:
    name: 🎉 Deploy Production
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code Production
      uses: actions/checkout@v3

    - name: Use Node.js 18 Production
      uses: actions/setup-node@v3
      with:
        node-version: '18'
      
    - name: 🔨 Build Project Production
      run: |
        npm install
        npm run build
    
    - name: List output files Production
      run: find out/ -print
      
    - name: 📂 Sync files Production
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ vars.FTP_URL }}
        username: ${{  vars.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: "ftps"
        local-dir: out/
        server-dir: "./"