on:
  push:
    branches:
      - development

name: 🚀 Deploy website Staging

jobs:
  web-deploy:
    name: 🎉 Deploy Staging
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code Staging
        uses: actions/checkout@v3

      - name: Use Node.js 18 Staging
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 🔨 Install dependencies
        run: npm ci

      - name: 🔨 Build Project Staging
        run: npm run build

      - name: 📦 Install partytown
        run: npm install "@builder.io/partytown"

      - name: 🚀 Deploy with partytown
        run: npx partytown copylib public/~partytown && npm run start

      - name: 📂 Sync files Staging
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_URL }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: "ftps"
          local-dir: out/
          server-dir: "./staging/"
          dangerous-clean-slate: true
