on:
  push:
    branches:
      - development
name: 🚀 Deploy website Staging
jobs:
  web-deploy:
    name: 🎉 Deploy Staging
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code Staging
        uses: actions/checkout@v3

      - name: Use Node.js 18 Staging
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 🔨 Build Project Staging
        run: |
          npm install
          npm run build

      - name: 📦 Install partytown
        run: npm install --save-dev "@builder.io/partytown"

      - name: 🚀 Deploy with partytown
        run: npm run partytown

      - name: List output files Staging
        run: find out/ -print

      - name: 📂 Sync files Staging
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ vars.FTP_URL }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: "ftps"
          local-dir: out/
          server-dir: "./staging/"
          dangerous-clean-slate: true
